/** @type {import('stylelint').Config} */
export default {
    extends: ["stylelint-config-standard-scss"],
    rules: {
        'alpha-value-notation': null,
        'at-rule-empty-line-before': null,
        'color-function-notation': null,
        'custom-property-empty-line-before': null,
        'declaration-block-no-redundant-longhand-properties': null,
        'declaration-block-no-shorthand-property-overrides': null,
        'declaration-empty-line-before': null,
        'font-family-no-missing-generic-family-keyword': null,
        'keyframes-name-pattern': null,
        'media-feature-range-notation': null,
        'no-descending-specificity': null,
        'no-empty-source': null,
        'property-no-vendor-prefix': null,
        'rule-empty-line-before': null,
        'scss/at-extend-no-missing-placeholder': null,
        'scss/at-mixin-argumentless-call-parentheses': null,
        'scss/at-mixin-pattern': null,
        'scss/at-rule-conditional-no-parentheses': null,
        'scss/comment-no-empty': null,
        'scss/dollar-variable-empty-line-before': null,
        'scss/dollar-variable-colon-space-before': null,
        'scss/dollar-variable-colon-space-after': null,
        'scss/dollar-variable-pattern': null,
        'scss/double-slash-comment-empty-line-before': null,
        'scss/double-slash-comment-whitespace-inside': null,
        'scss/no-global-function-names': null,
        'selector-attribute-quotes': null,
        'selector-class-pattern': null,
        'selector-pseudo-element-colon-notation': null,
        'selector-pseudo-element-no-unknown': [true, {
            "ignorePseudoElements": ["ng-deep"]
        }],
        'selector-type-no-unknown': null,
    },
};
