export enum Commands {
    FlashEraseAll = 0x01,
    FlashEraseRegion = 0x02,
    ReadMemory = 0x03,
    WriteMemory = 0x04,
    FillMemory = 0x05,
    FlashSecurityDisable = 0x06,
    GetProperty = 0x07,
    ReceiveSBFile = 0x08,
    Execute = 0x09,
    Call = 0x0A,
    Reset = 0x0B,
    SetProperty = 0x0C,
    FlashEraseAllUnsecure = 0x0D,
    FlashProgramOnce = 0x0E,
    FlashReadOnce = 0x0F,
    FlashReadResource = 0x10,
    ConfigureQuadSpi = 0x11,
    ReliableUpdate = 0x12,
    ConfigureI2c = 0xc1,
    ConfigureSpi = 0xc2,
    ConfigureCan = 0xc3
}
