export enum Properties {
    BootloaderVersion = 0x01,
    AvailablePeripherals = 0x02,
    FlashStartAddress = 0x03,
    FlashSize = 0x04,
    FlashSectorSize = 0x05,
    FlashBlockCount = 0x06,
    AvailableCommands = 0x07,
    CrcCheckStatus = 0x08,
    VerifyWrites = 0x0a,
    MaxPacketSize = 0x0b,
    ReservedRegions = 0x0c,
    ValidateRegions = 0x0d,
    RAMStartAddress = 0x0e,
    RAMSize = 0x0f,
    SystemDeviceIdent = 0x10,
    FlashSecurityState = 0x11,
    UniqueDeviceIdent = 0x12,
    FlashFacSupport = 0x13,
    FlashAccessSegmentSize = 0x14,
    FlashAccessSegmentCount = 0x15,
    FlashReadMargin = 0x16,
    QspiInitStatus = 0x17,
    TargetVersion = 0x18,
    ExternalMemoryAttributes = 0x19
}
