export const FIRMWARE_UPGRADE_METHODS = Object.freeze({
    KBOOT: 'kboot',
    MCUBOOT: 'mcuboot',
});

export type FIRMWARE_UPGRADE_METHODS_KEY_TYPE = keyof typeof FIRMWARE_UPGRADE_METHODS;
export type FIRMWARE_UPGRADE_METHODS_TYPE = typeof FIRMWARE_UPGRADE_METHODS[FIRMWARE_UPGRADE_METHODS_KEY_TYPE];
